[workspace]

[package]
name = "pmu"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.7.7"
bincode = "1.3.3"
bytes = "1.7.1"
chrono = "0.4.38"
circular-buffer = "0.1.8"
clap = { version = "4.0", features = ["derive"] }
crc = "3.2.1"                                          # May be only needed for dev
env_logger = "0.11.5"
femme = "2.2.1"
log = "0.4.22"
rand = "0.8.5"                                         #May be only needed for dev
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
