---
services:
  open-pdc:
    image: gridprotectionalliance/openpdc:v2.9.148
    container_name: openPDC
    networks:
      - pmu-network

    ports:
      - "8280:8280"
      - "8900:8900"

networks:
  pmu-network:
    driver: bridge
